#!/bin/bash

echo "=========================================="
echo "COPY THESE ENVIRONMENT VARIABLES TO NETLIFY"
echo "=========================================="
echo ""
echo "Go to: https://app.netlify.com/sites/starlit-mousse-8fa18a/settings/env"
echo ""
echo "Add these variables:"
echo ""
echo "Variable 1:"
echo "Key: NEXT_PUBLIC_SUPABASE_URL"
echo "Value: https://gualxudgbmpuhjbumfeh.supabase.co"
echo ""
echo "Variable 2:" 
echo "Key: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1YWx4dWRnYm1wdWhqYnVtZmVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjI5MTMsImV4cCI6MjA2NjIzODkxM30.t0m-kBXkyAWogfnDLLyXY1pl4oegxRmcvaG3NSs6rVM"
echo ""
echo "After adding these:"
echo "1. Click 'Save'"
echo "2. Trigger a new deploy from the Deploys tab"
echo "3. Or run: git commit --allow-empty -m 'Redeploy with env vars' && git push"
echo ""
echo "=========================================="