# This is a GitHub Actions workflow that can trigger the monitoring function
# Place this in .github/workflows/twitter-monitor.yml

name: Twitter Monitoring Cron
on:
  schedule:
    # Run every minute
    - cron: '* * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Twitter Monitoring
        run: |
          curl -X POST "https://gualxudgbmpuhjbumfeh.supabase.co/functions/v1/monitor-projects" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
        env:
          SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1YWx4dWRnYm1wdWhqYnVtZmVoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDY2MjkxMywiZXhwIjoyMDY2MjM4OTEzfQ.yFbFAuMR1kDsQ5Tni-FJIruKT9AmCsJg0uyNyEvNyH4